name: Generate Walrus Bump PR
run-name: Generate Walrus Bump PR

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-sui-testnet-version:
    name: Bump Walrus Version
    runs-on: ubuntu-ghcloud

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6.0.2

      - name: Bump
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        shell: bash
        run: |
          ./scripts/bump_walrus_version.sh
