name: Generate Walrus Bump PR
run-name: Generate Walrus Bump PR

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}

jobs:
  version-bump:
    name: Bump Walrus Version
    uses: ./.github/workflows/version-bump.yml
    with:
      type: minor
      delivery: pr
