name: Trigger Build Artifacts
run-name: Trigger Build Artifacts â†’ ${{ github.ref_name }}

on:
  workflow_dispatch:
  push:
    branches:
      - devnet
      - testnet
      - mainnet

concurrency: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  trigger-artifact-builds:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Walrus Artifact Builds in MystenLabs/sui-operations
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # pin@v4.0.1
        with:
          repository: MystenLabs/sui-operations
          token: ${{ secrets.SUI_OPS_DISPATCH_TOKEN }}
          event-type: walrus-build-artifacts
          client-payload: '{"branch": "${{ github.ref_name }}"}'
